### ISSUE TITLE
Scrollbar in navbar

### ISSUE THREAD

**Issue by Sakkov** [Sakkov/fiksukuljetus-website#41]
When the screen size is within the mobile breakpoint range, the mobile styling is activated as expected. However, on the desktop view, when a user hovers over a dropdown button in the navbar, the navbar suddenly expands in width, and a scrollbar appears.

**Comment by noviceCoder27** [comment]
will this fix be ok ? if so then I'd like to push the changes

![bug](https://user-images.githubusercontent.com/97236915/227785372-2f4bf223-326d-4b81-8520-90e5c08a865a.png)
