### ISSUE TITLE
Dropdown items unclickable in mobile view with mouse

### ISSUE THREAD

**Issue by Sakkov** [Sakkov/fiksukuljetus-website#42]
When the viewport size on the desktop is small enough, the mobile styling is applied, causing an issue with the dropdown items in the navbar. In this mobile view, the dropdown items are unclickable using the mouse pointer. They appear when hovering over the parent button in the navbar, but they disappear when the user tries to click on them. This issue affects the usability of the dropdown menus in the mobile styling on desktop.

Steps to reproduce:

Open the website on a desktop browser.
Reduce the viewport size until the mobile styling is applied.
Hover the cursor over any parent button in the navbar with dropdown items.
Try to click on one of the dropdown items.
Expected behavior:
The dropdown items should remain visible and clickable when the user hovers over them and tries to click on them.

Actual behavior:
The dropdown items appear when hovering over the parent button but disappear when attempting to click on them, making them unclickable.

Possible solution:
Investigate the CSS and JavaScript related to the dropdown menus in the mobile styling. Ensure that the hover and click events are properly handled for both the parent button and the dropdown items. Modify the CSS and/or JavaScript as necessary to ensure the dropdown items remain visible and clickable when using the mobile styling on a desktop browser.

**Comment by noviceCoder27** [comment]
Will this solution work? 

https://user-images.githubusercontent.com/97236915/227790156-378bcf70-29d3-4d58-9732-baf7039d0109.mp4
